config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root controller: :stock, action: :index

  get '/users/:user_id/stock' => 'stock#index', as: 'user_stock_index'
  get '/stocks' => 'stock#show', as: 'stock_show'
  get '/users/:user_id/transaction' => 'transaction#index', as: 'user_transaction_index'
  get '/users/:user_id/transaction/new'=> 'transaction#new',  as:'new_user_transaction' 
  post '/users/:user_id/transaction'=> 'transaction#create',  as: 'user_transaction'


end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark justify-content-between" style="background-color: #3b5998">
  <div class="logo">
        <a href="/">

            <span><i class="fas fa-shekel-sign"></i>MetaStock</span>
        </a>
      
  </div>

  <div class="navbar d-flex justify-content-end">
    <div class="navbar-nav ">
            <%=  link_to "Portfolio", user_stock_index_url(current_user.id), class: "nav-item nav-link"  %>  
            <%=  link_to "Transactions", user_transaction_index_url(current_user.id), class: "nav-item nav-link"  %>            
            <%=  link_to "Market Summary", stock_show_url, class: "nav-item nav-link"  %>       
        <% if current_user %>
            <div class="dropdown">
                <a class="navbar-link dropdown-toggle"  data-toggle="dropdown"  href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img class="avatar" src="https://s.gravatar.com/avatar/ea8be90cf21a6f11a0e5a1cd9b9ebc47?s=80">
                <%= current_user.username %>
                </a>
            
                <div class="dropdown-menu" > 
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
            </div>
        <% end %>
    </div>
</div>
 
</nav>