config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root controller: :stock, action: :index

  get '/users/:user_id/stock' => 'stock#index', as: 'user_stock_index'
  get '/stocks' => 'stock#show', as: 'stock_show'
  get '/users/:user_id/transaction' => 'transaction#index', as: 'user_transaction_index'
  get '/users/:user_id/transaction/new'=> 'transaction#new',  as:'new_user_transaction' 
  post '/users/:user_id/transaction'=> 'transaction#create',  as: 'user_transaction'


end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :transactions
    has_many :users, through: :transactions
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
    before_action :load_api, only: [:index,:show]

    require 'net/http'
    def index
        @user        = current_user
        @stocks      = User.find(current_user.id).stocks.uniq ||=nil
        @stock_data  = Hash.new
        @stocks.each do |stock|
            quantity = 0
            
            total_price = 0

            quote = @client.quote(stock.symbol)

            price = quote.latest_price
            change_percent = quote.change_percent_s

            @user.transactions.where(stock_id: stock.id).each do |st|
                quantity = quantity + st.quantity
            end

            @user.transactions.where(stock_id: stock.id).each do |st|
                total_price = total_price + st.purchase_price
            end

            @stock_data[stock.symbol] = [quantity, price, change_percent, total_price]
        end
        @transaction = Transaction.new(user_id: current_user.id)
        @transaction.build_stock   
    end 

    def create
    end 

    def show  
         uri = URI('https://sandbox.iexapis.com/stable/stock/market/list/mostactive?token=Tsk_abb3bfef5bac4820b058ea01006a8627&listLimit=100')
         @request_api = Net::HTTP.get(uri)
         @most_active = JSON.parse(@request_api)
        
    end       


    private

    def load_api
        @client = IEX::Api::Client.new(
            publishable_token: ENV['SAND_BOX_KEY'],
            endpoint: 'https://sandbox.iexapis.com/v1'
          )
    end

    def stock_params
        params.require(:stock).permit(:symbol)
    end

end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/stock/index.html.erb
<%= render partial: 'shared/navbar' %>
<% if flash[:error]%>
            <div class="alert alert-danger" role="alert">
                    <%=  flash[:error] %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
<%end%>
    
<div class="portfolio-container">
       
    <div class="portfolio-table">
        <div class="header-container">
            <h1 class="header__text">Your Portfolio</h1>
            <h3 class="header__text balance">Balance: <%= number_to_currency(@user.balance, precision:2) %></h3>
        </div>
           <% if @stocks.size > 0 %>
            <table class="table">
             <thead> 
                <tr >
                <th scope="col">Ticker Symbol</th>
                <th scope="col">Change</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Total Cost </th>
                </tr>
             </thead>
             <tbody> 
            <% @stock_data.each do |symbol, stock_data| %>
                <tr>
                 <td class="highlight-primary"><%= symbol %></td> 
                <td class="highlight-primary"><%= stock_data[2]%></td>
                <td ><%= pluralize(stock_data[0], 'share')%></td>
                <td class="highlight-primary"><%= number_to_currency(stock_data[1], precision: 2)%></td>
                <td class="highlight-secondary"><%= number_to_currency(stock_data[3], precision:2)%></td>
                </tr>
            <% end %>
            </tbody>
            </table>
        <% else %>
            <p>No stocks yet</p>
        <% end %>
    </div>

    <div class="stock-form">
    <h3>Buy Stocks</h3>
    <%= simple_form_for @transaction, :url => user_transaction_path(@user.id) do |form| %>
        <%= form.simple_fields_for :stock do |st| %>
                <div class="form-group">
                <%= st.input :symbol, as: :string,
                                        wrapper: false,
                                        required: false,
                                        label: "Ticker Symbol",
                                        input_html: {
                                            class: 'form-control',
                                        } %>
                </div>
        <% end %>
        <div class="form-group">
                <%= form.input :quantity, as: :integer,
                                        wrapper: false,
                                        required: false,
                                        label: "Quantity",
                                        input_html: {
                                            class: 'form-control',
                                        
                                        } %>
        </div>
        <%= form.hidden_field :user_id, { :value => @user.id } %>
        <%= form.submit "Buy", class: 'btn-stock' %>
    <%end%>

</div>

app/views/stock/show.html.erb
<%= render partial: 'shared/navbar' %>
<div class="portfolio-container">
    <div class="portfolio-table">
        <div class="header-container">
            <h1 class="header__text">Market Summary</h1>
        </div>
            <table class="table" id="table"
                                 data-toggle="table"
                                 data-height="500"
                                 data-custom-sort="customSort">
            <thead>
                <tr>
                    <th scope="col"> Symbol</th>
                    <th scope="col" >Company Name</th>
                    <th scope="col"  data-field="change" data-sortable="true">Change</th>
                    <th scope="col"  data-field="open" data-sortable="true">Open</th>
                    <th scope="col"  data-field="high" data-sortable="true">High</th>
                    <th scope="col"  data-field="low" data-sortable="true">Low</th>
                    <th scope="col"  data-field="Previous Close" data-sortable="true">Previous Close</th>
                    <th scope="col"  data-field="volume" data-sortable="true">Volume</th>
                    <th scope="col"  data-field="Current Value" data-sortable="true">Current Value</th>
                </tr>
            </thead>
            <tbody>
             <% @most_active.each do |key, value|%>
                <tr>
                    <td ><%= key["symbol"] %></td> 
                    <td ><%= key["companyName"]%></td> 
                    <td ><%= number_to_percentage(key["changePercent"], precision: 2)%></td> 
                    <td ><%= key["open"]%></td> 
                    <td ><%= key["high"]%></td> 
                    <td ><%= key["low"] %></td> 
                    <td ><%= number_to_currency(key["volume"], precision: 2)%></td> 
                    <td ><%= number_to_currency(key["previousClose"], precision: 2)%></td> 
                    <td ><%= number_to_currency(key["latestPrice"], precision: 2)%></td>  
                </tr>
            <% end %>
            </tbody>
            </table>

    </div>
    
</div>